{% set name = "influxdb" %}
{% set version = "5.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46f85e7b04ee4b3dee894672be6a295c94709003a7ddea8820deec2ac4d8b27a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
  run:
    - msgpack-python
    - requests >=2.17.0
    - six >=1.10.0
    - python
    - python-dateutil >=2.6.0
    - pytz

test:
  imports:
    - influxdb

about:
  home: https://github.com/influxdata/influxdb-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python client for InfluxDB
  description: |
    InfluxDB-Python is a client for interacting with InfluxDB. InfluxDB is an 
    open-source distributed time series database, find more about InfluxDB at 
    https://docs.influxdata.com/influxdb/latest
  doc_url: http://simplejson.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - DanielBok
