travis:
  secure:
    BINSTAR_TOKEN: F0PlSsUac/cuEuUzPLu4z+PEYQ3r7fOkC5M947y7ZNNLQG2mFH+L8ZGCBAMlTvbtKB4n1T097pI0kPMtU4DuZmCGUQWI8bf0lbeNbNVshfKNYNdXlMheiGOFtNdMosJNItv3BtoBYlLS2/H/bpsiUF+TdTt0z0yT2zW9KVBwDT8eVHSQoHKMiPAfP+esG8S9mgfeF/PnReSnIFTp8ExwnPd0VYBKB3oGK3DkRaF81kHY8qX9VWQT2q9m4V6+InUP21IN26KWG0r/kU02r7qWesWtc76ScOt+bSfOZ7zZk+n/mrjtulS81dVBG2+775e/c6E9cwNABR0RWksxQ+lT4WVzqHw4z8keAXW/7Ayzw6l6AMDuMGo7repCa13l917zZODkTWS8q6E+EYd8jOTrAwhwbLWrNZwEUaaty9At+kGaUcVQQupHNDzvC1z0Koyx3u/UNfvh2KRLHEdA/yAChl12p3fhToiagQV/e8aZoUfyt1un6DByt5cpy+tYHDBEHmb/iKVGX84Y37z6Iy9w1s4kQ2SlRZnOiIypQx0x3P+Sm+zMcPsyiUbXIELr0eaovu4Vuaq56sYWLugt7cRDlmeMQbh9VIJTkJ8QVcbe6fjMnbsgVsQvOjfxK0Dg+cfZPk7YorOawGlV01Kel0FZ+g3IVEWUbqDm38dH+kB9qNM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
